#!/bin/sh

# command to split data_example.csv into equal parts: split -l 20000000 data_example.csv data_example.log.
# then do 
# cat data_example.log.aa >> data_example.log.ab
# cat data_example.log.ab >> data_example.log.ac
# cat data_example.log.ac >> data_example.log.ad
# cat data_example.log.ad >> data_example.log.ae

INPUT_FILES="./data_example.csv.log.*"
SCHEMA_FILE="./schema_example2.json"
OUT_INDEX="./out_index"
SORT_ATTRS="cgpa"

for file in $( ls $INPUT_FILES); do
	echo "Running bsort with file $file"

	for j in `seq 1 3`; do
		echo "Run $j"
		./bsort $SCHEMA_FILE ./$file $OUT_INDEX $SORT_ATTRS
		rm -rf leveldb_dir
		rm -f out_index
	done
done
